// This file is autogenerated by ansvia-vscode
// don't edit by hand or your changes will lost without you knowing
class ErrorCode {
  // Sukses atau tidak terjadi error.
  static const int noError = 0;

  // Unauthorized
  static const int unauthorized = 3000;

  // Kegagalan yang berkaitan dengan proses serialize/deserialize data.
  static const int serializeDeserializeError = 4001;

  // Parameter tidak lengkap/kurang.
  static const int invalidParameter = 4002;

  // Message tidak ada signature-nya, dibutuhkan untuk verifikasi menggunakan public key.
  static const int messageHasNoSign = 4003;

  // Tidak ada informasi login.
  static const int noLoginInfo = 4004;

  // Pengirim dan penerima alamatnya sama.
  static const int fromAndToTargetIsSame = 4005;

  // Kegagalan yang tidak diketahui penyebabnya.
  static const int unknownError = 5001;

  // Kegagalan pada database internal apabila terjadi error.
  static const int databaseError = 6001;

  // Kegagalan pada database yang berkaitan dengan
  // ketidakditemukannya record/data di dalam database.
  static const int databaseRecordNotFoundError = 6002;

}