// This file is autogenerated by ansvia-vscode
// don't edit by hand or your changes will lost without you knowing
class FeedKind {
  // Feed are created by system
  static const int systemFeed = 0;

  // Merupakan feed yang memberikan informasi pengumuman secara global,
  // feed ini tidak ada creatornya atau creatornya adalah system.
  static const int announcement = 1;

  // When new cases found
  static const int newCases = 2;

  // When new deaths record found
  static const int newDeaths = 3;

  // When new recovered record found
  static const int newRecovered = 4;

  // Info
  static const int info = 6;

}