// This file is autogenerated by ansvia-vscode
// don't edit by hand or your changes will lost without you knowing
class MapMarkerKind {
  // Unknown type
  static const int unknown = 0;

  // Pandemic information type
  static const int pandemicInfo = 1;

  // Sick
  static const int sick = 2;

  // Fasilitas kesehatan (Faskes) bertipe Rumah Sakit
  static const int hospital = 3;

}