CREATE TABLE notifs (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  kind SMALLINT NOT NULL, -- See types::NotifKind
  "text" VARCHAR NOT NULL,
  initiator_id BIGINT NOT NULL DEFAULT 0,
  receiver_id BIGINT NOT NULL DEFAULT 0 REFERENCES users(id) ON DELETE SET DEFAULT,
  "read" BOOLEAN NOT NULL DEFAULT FALSE,
  keywords TEXT[] NOT NULL DEFAULT '{}',
  meta TEXT[] NOT NULL DEFAULT '{}',
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

