// This file is autogenerated by ansvia-vscode
// don't edit by hand or your changes will lost without you knowing
export default class ErrorCode {
  // Sukses atau tidak terjadi error.
  static NoError = 0;

  // Unauthorized
  static Unauthorized = 3000;

  // Kegagalan yang berkaitan dengan proses serialize/deserialize data.
  static SerializeDeserializeError = 4001;

  // Parameter tidak lengkap/kurang.
  static InvalidParameter = 4002;

  // Message tidak ada signature-nya, dibutuhkan untuk verifikasi menggunakan public key.
  static MessageHasNoSign = 4003;

  // Tidak ada informasi login.
  static NoLoginInfo = 4004;

  // Pengirim dan penerima alamatnya sama.
  static FromAndToTargetIsSame = 4005;

  // Kegagalan yang tidak diketahui penyebabnya.
  static UnknownError = 5001;

  // Kegagalan pada database internal apabila terjadi error.
  static DatabaseError = 6001;

  // Kegagalan pada database yang berkaitan dengan
  // ketidakditemukannya record/data di dalam database.
  static DatabaseRecordNotFoundError = 6002;

}