CREATE TABLE logs (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  activity TEXT NOT NULL,
  initiator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  meta TEXT[] NOT NULL DEFAULT '{}',
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
