// this code is autogenerated by ansvia-vscode extension.
// please don't edit this by hand
// use 'ansvia-vscode extension > Edit Model fields' instead.
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

/// Model for Feed
@immutable
class Feed extends Equatable {
  final int id;
  final int creatorId;
  final String creatorName;
  final String loc;
  final int kind;
  final String text;
  final List<String> hashtags;
  final List<String> meta;
  final String ts;

  Feed(this.id, this.creatorId, this.creatorName, this.loc, this.kind,
      this.text, this.hashtags, this.meta, this.ts)
      : super(
            [id, creatorId, creatorName, loc, kind, text, hashtags, meta, ts]);

  Map<String, dynamic> toMap() {
    Map<String, dynamic> data = Map();
    data["id"] = this.id;
    data["creator_id"] = this.creatorId;
    data["creator_name"] = this.creatorName;
    data["loc"] = this.loc;
    data["kind"] = this.kind;
    data["text"] = this.text;
    data["hashtags"] = this.hashtags;
    data["meta"] = this.meta;
    data["ts"] = this.ts;
    return data;
  }

  static Feed fromMap(Map<String, dynamic> data) {
    assert(data['creator_id'] != null, "Feed.creator_id is null");
    assert(data['creator_name'] != null, "Feed.creator_name is null");
    assert(data['loc'] != null, "Feed.loc is null");
    assert(data['kind'] != null, "Feed.kind is null");
    assert(data['text'] != null, "Feed.text is null");
    assert(data['ts'] != null, "Feed.ts is null");
    return Feed(
        data['id'] as int,
        data['creator_id'] as int,
        data['creator_name'] as String,
        data['loc'] as String,
        data['kind'] as int,
        data['text'] as String,
        data['hashtags'] != null ? List.from(data['hashtags']) : [],
        data['meta'] != null ? List.from(data['meta']) : [],
        data['ts'] as String);
  }

  Feed copy(
      {int creatorId,
      String creatorName,
      String loc,
      int kind,
      String text,
      List<String> hashtags,
      List<String> meta,
      String ts}) {
    return Feed(
        this.id,
        creatorId ?? this.creatorId,
        creatorName ?? this.creatorName,
        loc ?? this.loc,
        kind ?? this.kind,
        text ?? this.text,
        hashtags ?? this.hashtags,
        meta ?? this.meta,
        ts ?? this.ts);
  }
}
