// this code is autogenerated by ansvia-vscode extension.
// please don't edit this by hand
// use 'ansvia-vscode extension > Edit Model fields' instead.
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

/// Model for MapMarker
@immutable
class MapMarker extends Equatable {
  final double longitude;
  final double latitude;
  final int kind;
  final String caption;

  MapMarker(this.longitude, this.latitude, this.kind, this.caption)
      : super([longitude, latitude, kind, caption]);

  Map<String, dynamic> toMap() {
    Map<String, dynamic> data = Map();
    data["longitude"] = this.longitude;
    data["latitude"] = this.latitude;
    data["kind"] = this.kind;
    data["caption"] = this.caption;
    return data;
  }

  static MapMarker fromMap(Map<String, dynamic> data) {
    assert(data['longitude'] != null, "MapMarker.longitude is null");
    assert(data['latitude'] != null, "MapMarker.latitude is null");
    assert(data['kind'] != null, "MapMarker.kind is null");
    assert(data['caption'] != null, "MapMarker.caption is null");
    return MapMarker(
        data['longitude'] as double,
        data['latitude'] as double,
        data['kind'] as int,
        data['caption'] as String);
  }

  MapMarker copy(
      {double longitude, double latitude, int kind, String caption}) {
    return MapMarker(longitude ?? this.longitude,
        latitude ?? this.latitude, kind ?? this.kind, caption ?? this.caption);
  }
}
