// this code is autogenerated by ansvia-vscode extension.
// please don't edit this by hand
// use 'ansvia-vscode extension > Edit Model fields' instead.
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

/// Model for MapLocation
@immutable
class MapLocation extends Equatable {
  final int id;
  final double lat;
  final double long;

  MapLocation(this.id, this.lat, this.long) : super([id, lat, long]);

  Map<String, dynamic> toMap() {
    Map<String, dynamic> data = Map();
    data["id"] = this.id;
    data["lat"] = this.lat;
    data["long"] = this.long;
    return data;
  }

  static MapLocation fromMap(Map<String, dynamic> data) {
    assert(data['lat'] != null, "Map.lat is null");
    assert(data['long'] != null, "Map.long is null");
    return MapLocation(
        data['id'] as int, data['lat'] as double, data['long'] as double);
  }

  MapLocation copy({double lat, double long}) {
    return MapLocation(this.id, lat ?? this.lat, long ?? this.long);
  }
}
