// this code is autogenerated by ansvia-vscode extension.
// please don't edit this by hand
// use 'ansvia-vscode extension > Edit Model fields' instead.
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

/// Model for OccupationInfoDetail
@immutable
class OccupationInfoDetail extends Equatable {
  final int id;
  final int vacTotal;
  final int usedTotal;
  final int waiting;
  final String lastUpdated;

  OccupationInfoDetail(
      this.id, this.vacTotal, this.usedTotal, this.waiting, this.lastUpdated)
      : super([id, vacTotal, usedTotal, waiting, lastUpdated]);

  Map<String, dynamic> toMap() {
    Map<String, dynamic> data = Map();
    data["id"] = this.id;
    data["vac_total"] = this.vacTotal;
    data["used_total"] = this.usedTotal;
    data["waiting"] = this.waiting;
    data["last_updated"] = this.lastUpdated;
    return data;
  }

  static OccupationInfoDetail fromMap(Map<String, dynamic> data) {
    assert(data['vac_total'] != null, "OccupationInfoDetail.vac_total is null");
    assert(
        data['used_total'] != null, "OccupationInfoDetail.used_total is null");
    assert(data['waiting'] != null, "OccupationInfoDetail.waiting is null");
    assert(data['last_updated'] != null,
        "OccupationInfoDetail.last_updated is null");
    return OccupationInfoDetail(
        data['id'] as int,
        data['vac_total'] as int,
        data['used_total'] as int,
        data['waiting'] as int,
        data['last_updated'] as String);
  }

  OccupationInfoDetail copy(
      {int vacTotal, int usedTotal, int waiting, String lastUpdated}) {
    return OccupationInfoDetail(
        this.id,
        vacTotal ?? this.vacTotal,
        usedTotal ?? this.usedTotal,
        waiting ?? this.waiting,
        lastUpdated ?? this.lastUpdated);
  }
}
