// this code is autogenerated by ansvia-vscode extension.
// please don't edit this by hand
// use 'ansvia-vscode extension > Edit Model fields' instead.
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

/// Model for PandemicInfoDetail
@immutable
class PandemicInfoDetail extends Equatable {
  final int id;
  final int totalCases;
  final int totalDeaths;
  final int totalRecovered;

  PandemicInfoDetail(
      this.id, this.totalCases, this.totalDeaths, this.totalRecovered)
      : super([id, totalCases, totalDeaths, totalRecovered]);

  Map<String, dynamic> toMap() {
    Map<String, dynamic> data = Map();
    data["id"] = this.id;
    data["total_cases"] = this.totalCases;
    data["total_deaths"] = this.totalDeaths;
    data["total_recovered"] = this.totalRecovered;
    return data;
  }

  static PandemicInfoDetail fromMap(Map<String, dynamic> data) {
    assert(
        data['total_cases'] != null, "PandemicInfoDetail.total_cases is null");
    assert(data['total_deaths'] != null,
        "PandemicInfoDetail.total_deaths is null");
    assert(data['total_recovered'] != null,
        "PandemicInfoDetail.total_recovered is null");
    return PandemicInfoDetail(data['id'] as int, data['total_cases'] as int,
        data['total_deaths'] as int, data['total_recovered'] as int);
  }

  PandemicInfoDetail copy(
      {int totalCases, int totalDeaths, int totalRecovered}) {
    return PandemicInfoDetail(this.id, totalCases ?? this.totalCases,
        totalDeaths ?? this.totalDeaths, totalRecovered ?? this.totalRecovered);
  }
}
