// this code is autogenerated by ansvia-vscode extension.
// please don't edit this by hand
// use 'ansvia-vscode extension > Edit Model fields' instead.
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

/// Model for ReportNote
@immutable
class ReportNote extends Equatable {
  final int id;
  final String title;
  final String notes;
  final int creatorId;
  final String creatorName;
  final List<String> meta;
  final String ts;
  final String location;

  ReportNote(this.id, this.title, this.notes, this.creatorId, this.creatorName,
      this.meta, this.ts, this.location)
      : super([id, title, notes, creatorId, creatorName, meta, ts, location]);

  Map<String, dynamic> toMap() {
    Map<String, dynamic> data = Map();
    data["id"] = this.id;
    data["title"] = this.title;
    data["notes"] = this.notes;
    data["creator_id"] = this.creatorId;
    data["creator_name"] = this.creatorName;
    data["meta"] = this.meta;
    data["ts"] = this.ts;
    data["location"] = this.location;
    return data;
  }

  static ReportNote fromMap(Map<String, dynamic> data) {
    assert(data['title'] != null, "ReportNote.title is null");
    assert(data['notes'] != null, "ReportNote.notes is null");
    assert(data['creator_id'] != null, "ReportNote.creator_id is null");
    assert(data['creator_name'] != null, "ReportNote.creator_name is null");
    assert(data['ts'] != null, "ReportNote.ts is null");
    assert(data['location'] != null, "ReportNote.location is null");
    return ReportNote(
        data['id'] as int,
        data['title'] as String,
        data['notes'] as String,
        data['creator_id'] as int,
        data['creator_name'] as String,
        data['meta'] != null ? List.from(data['meta']) : [],
        data['ts'] as String,
        data['location'] as String);
  }

  ReportNote copy(
      {String title,
      String notes,
      int creatorId,
      String creatorName,
      List<String> meta,
      String ts,
      String location}) {
    return ReportNote(
        this.id,
        title ?? this.title,
        notes ?? this.notes,
        creatorId ?? this.creatorId,
        creatorName ?? this.creatorName,
        meta ?? this.meta,
        ts ?? this.ts,
        location ?? this.location);
  }
}
