// this code is autogenerated by ansvia-vscode extension.
// please don't edit this by hand
// use 'ansvia-vscode extension > Edit Model fields' instead.
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';
import 'package:pandemia_mobile/models/user_settings.dart';

/// Model for User
@immutable
class User extends Equatable {
  final int id;
  final String fullName;
  final String email;
  final UserSettings settings; // Nullable

  User(this.id, this.fullName, this.email, this.settings)
      : super([id, fullName, email, settings]);

  Map<String, dynamic> toMap() {
    Map<String, dynamic> data = Map();
    data["id"] = this.id;
    data["full_name"] = this.fullName;
    data["email"] = this.email;
    data["settings"] = this.settings != null ? this.settings.toMap() : null;
    return data;
  }

  static User fromMap(Map<String, dynamic> data) {
    assert(data['full_name'] != null, "User.full_name is null");
    assert(data['email'] != null, "User.email is null");
    return User(
        data['id'] as int,
        data['full_name'] as String,
        data['email'] as String,
        data['settings'] != null
            ? UserSettings.fromMap(data['settings'])
            : null);
  }

  User copy({String fullName, String email, UserSettings settings}) {
    return User(this.id, fullName ?? this.fullName, email ?? this.email,
        settings ?? this.settings);
  }
}
