// this code is autogenerated by ansvia-vscode extension.
// please don't edit this by hand
// use 'ansvia-vscode extension > Edit Model fields' instead.
import 'package:equatable/equatable.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:meta/meta.dart';
import 'package:pandemia_mobile/models/user_settings.dart';

/// Model for User
@immutable
class User extends Equatable {
  final int id;
  final String fullName;
  final String email;
  final String phoneNum;
  final bool isSatgas;
  final UserSettings settings; // Nullable
  final LatLng loc; // Nullable

  User(this.id, this.fullName, this.email, this.phoneNum, this.isSatgas,
      this.settings, this.loc)
      : super([id, fullName, email, phoneNum, isSatgas, settings, loc]);

  Map<String, dynamic> toMap() {
    Map<String, dynamic> data = Map();
    data["id"] = this.id;
    data["full_name"] = this.fullName;
    data["email"] = this.email;
    data["phone_num"] = this.phoneNum;
    data["is_satgas"] = this.isSatgas;
    data["settings"] = this.settings != null ? this.settings.toMap() : null;
    data["loc"] = this.loc != null ? this.loc : null;
    return data;
  }

  static User fromMap(Map<String, dynamic> data) {
    assert(data['full_name'] != null, "User.full_name is null");
    assert(data['email'] != null, "User.email is null");
    return User(
        data['id'] as int,
        data['full_name'] as String,
        data['email'] as String,
        data['phone_num'] as String,
        data['is_satgas'] as bool,
        data['settings'] != null
            ? UserSettings.fromMap(data['settings'])
            : null,
        data['loc'] != null
            ? LatLng(data['loc']['lat'], data['loc']['long'])
            : null);
  }

  User copy(
      {String fullName,
      String email,
      String phoneNum,
      bool isSatgas,
      UserSettings settings,
      LatLng loc}) {
    return User(
        this.id,
        fullName ?? this.fullName,
        email ?? this.email,
        phoneNum ?? this.phoneNum,
        isSatgas ?? this.isSatgas,
        settings ?? this.settings,
        loc ?? this.loc);
  }
}
