ALTER TABLE records ADD COLUMN ppdwt INT NOT NULL DEFAULT 0;
ALTER TABLE records ADD COLUMN pptb INT NOT NULL DEFAULT 0;
ALTER TABLE records ADD COLUMN odp INT NOT NULL DEFAULT 0;
ALTER TABLE records ADD COLUMN odpsp INT NOT NULL DEFAULT 0;
ALTER TABLE records ADD COLUMN pdp INT NOT NULL DEFAULT 0;
ALTER TABLE records ADD COLUMN pdps INT NOT NULL DEFAULT 0;
ALTER TABLE records ADD COLUMN pdpm INT NOT NULL DEFAULT 0;
ALTER TABLE records ADD COLUMN otg INT NOT NULL DEFAULT 0;

ALTER TABLE records ADD COLUMN loc_path TEXT NOT NULL DEFAULT '';

CREATE INDEX idx_records_meta ON records USING GIN(meta);
CREATE INDEX idx_records_loc_path ON records(meta);



