ALTER TABLE village_data ADD COLUMN ppdwt INT NOT NULL DEFAULT 0;
ALTER TABLE village_data ADD COLUMN pptb INT NOT NULL DEFAULT 0;
ALTER TABLE village_data ADD COLUMN odpsp INT NOT NULL DEFAULT 0;
ALTER TABLE village_data ADD COLUMN pdps INT NOT NULL DEFAULT 0;
ALTER TABLE village_data ADD COLUMN pdpm INT NOT NULL DEFAULT 0;
ALTER TABLE village_data ADD COLUMN otg INT NOT NULL DEFAULT 0;

ALTER TABLE district_data ADD COLUMN ppdwt INT NOT NULL DEFAULT 0;
ALTER TABLE district_data ADD COLUMN pptb INT NOT NULL DEFAULT 0;
ALTER TABLE district_data ADD COLUMN odpsp INT NOT NULL DEFAULT 0;
ALTER TABLE district_data ADD COLUMN pdps INT NOT NULL DEFAULT 0;
ALTER TABLE district_data ADD COLUMN pdpm INT NOT NULL DEFAULT 0;
ALTER TABLE district_data ADD COLUMN otg INT NOT NULL DEFAULT 0;

