List<String> kab = [
    "Cilacap"
    "Banyumas",
    "Purbalingga",
    "Banjarnegara",
    "Kebumen",
    "Purworejo",
    "Wonosobo",
    "Magelang",
    "Boyolali",
    "Klaten",
    "Sukoharjo",
    "Wonogiri",
    "Karanganyar",
    "Sragen",
    "Grobogan",
    "Blora",
    "Rembang",
    "Pati",
    "Kudus",
    "Jepara",
    "Demak",
    "Semarang",
    "Temanggung",
    "Kendal",
    "Batang",
    "Pekalongan",
    "Pemalang",
    "Tegal",
    "Brebes",
    "Kota Magelang",
    "Kota Surakarta",
    "Kota Salatiga",
    "Kota Semarang",
    "Kota Pekalongan",
    "Kota Tegal"
    "Bantul",
    "Gunungkidul",
    "Kulon Progo",
    "Sleman",
    "Kota Yogyakarta",
    "Aceh Barat", //Provinsi Aceh
    "Aceh Barat Daya",
    "Aceh Besar",
    "Aceh Jaya",
    "Aceh Selatan",
    "Aceh Singkil",
    "Aceh Tamiang",
    "Aceh Tengah",
    "Aceh Tenggara",
    "Aceh Timur",
    "Aceh Utara",
    "Bener Meriah",
    "Bireuen",
    "Gayo Lues",
    "Nagan Raya",
    "Pidie",
    "Pidie Jaya",
    "Simeulue",
    "Banda Aceh",
    "Langsa",
    "Lhoksumawe",
    "Subulussalam",
    "Asahan", // Provinsi Sumatra Utama
    "Batu Bara",
    "Dairi",
    "Deli Serdang",
    "Humbang Hasundutan",
    "Karo",
    "Labuhan Batu",
    "Labuhan Batu Selatan",
    "Labuhan Batu Utara",
    "Langkat",
    "Mandailing Natal",
    "Nias",
    "Nias Barat",
    "Nias Selatan",
    "Nias Utara",
    "Padang Lawas",
    "Padang Lawas Utara",
    "Pakpak Bharat",
    "Samosir",
    "Serdang Bedagai",
    "Simalungun",
    "Tapanuli Selatan",
    "Tapanuli Tengah",
    "Tapanuli Utara",
    "Toba Samosir",
    "Binjai"
    "Gunung Sitoli",
    "Medan",
    "Padang Sidempuan",
    "Pematangsiantar",
    "Sibolga",
    "Tanjungbalai",
    "Tebing Tinggi",
    "Agam", // Provinsi Sumatra Barat
    "Dharmasraya",
    "Kepulauan Mentawai",
    "Lima Puluh Kota",
    "Padang Pariaman",
    "Pasaman",
    "Pasaman Barat",
    "Pesisir Selatan",
    "Sijunjung",
    "Kapupaten Solok",
    "Solok Selatan",
    "Tanah Datar",
    "Bukittinggi",
    "Padang",
    "Pandangpanjang",
    "Pariaman",
    "Payakumbuh",
    "Sawahlunto",
    "Solok",
    "Bengkalis", // Provinsi Riau
    "Indragiri Hilir",
    "Indragiri Hulu",
    "Kampar",
    "Kepuaulan Meranti",
    "Kuantan Singingi",
    "Pelalawan",
    "Rokan Hilir",
    "Rokan Hulu",
    "Siak",
    "Damai",
    "Pekanbaru",
    "Bintan", // Kep. Riau
    "Karimun",
    "Kepulauan Anambas",
    "Lingga",
    "Natuna",
    "Batam",
    "Tanjungpinang",
    "Batanghari", //Provinsi Jambi
    "Bungo",
    "Kerinci",
    "Merangin",
    "Muaro Jambi",
    "Sarolangun",
    "Tanjung Jabung Barat",
    "Tanjung Jabung Timur",
    "Tebo",
    "Kota Jambi",
    "Sungaipenuh",
    "Bengkulu Selatan", //Provinsi Bengkulu
    "Bengkulu Tengah",
    "Bengkulu Utara",
    "Kaur",
    "Kepahiang",
    "Lebong",
    "Mukomuko",
    "Rejang Lebong",
    "Seluma",
    "Kota Bengkulu",
    "Banyuasin", // Provinsi Sumatra Selatan
    "Empat Lawang",
    "Lahat",
    "Muara Enim",
    "Musi Banyuasin",
    "Musi Rawas",
    "Musi Rawas Utara",
    "Ogan Hilir",
    "Ogan Komering Ulu",
    "Ogan Komering Ulu Selatan",
    "Ogan Komering Ulu Timur",
    "Penukal Abab Lematang Ilir",
    "Lubuklinggau",
    "Pagar Alam",
    "Palembang",
    "Prabumulih",
    "Bangka", // Provinsi Babel
    "Bangka Barat",
    "Bangka Selatan",
    "Bangka Tengah",
    "Belitung",
    "Belitung Timur",
    "Pangkalpinang",
    "Lampung Barat", // Provinsi Lampung
    "Lampung Selatan",
    "Lampung Tengah",
    "Lampung Timur",
    "Lampung Utara",
    "Mesuji",
    "Peswaran",
    "Pesisir Barat",
    "Pringsewu",
    "Tanggamus",
    "Tulang Bawang",
    "Tulang Bawang Barat",
    "Way Kanan",
    "Bandar Lampung",
    "Metro",
    "Lebak", // Provinsi Banten
    "Pandeglang",
    "Kabupaten Serang",
    "Kabupaten Tangerang",
    "Cilegon",
    "Serang",
    "Tangerang",
    "Tangerang Selatan",
	"Buru", //Provinsi Maluku
	"Buru Selatan",
	"Kepulauan Aru",
	"Maluku Barat Daya",
	"Maluku Tengah",
	"Maluku Tenggara",
	"Kepulauan Tanimbar",
	"Seram Bagian Barat",
	"Seram Bagian Timur",
	"Ambon",
	"Tual",
	"Halmahera Barat", // Provinsi Maluku Utara
	"Halmahera Tengah",
	"Halmahera Timur",
	"Halmahera Selatan",
	"Halmahera Utara",
	"Kepulauan Sula",
	"Pulau Morotai",
	"Pulau Taliabu",
	"Ternate",
	"Tidore Kepulauan",
	"Asmat", // Provinsi Papua
	"Biak Numfor",
	"Boven Dogoel",
  "Deiyai",
  "Dogiyai",
  "Intan Jaya",
  "Jayapura",
  "Jayawijaya",
  "Keerom",
  "Kepulauan Yapen",
  "Lanny Jaya",
  "Mamberamo Raya",
  "Mamberamo Tengah",
  "Mappi",
  "Merauke",
  "Mimika",
  "Nabire",
  "Nduga",
  "Paniai",
  "Pegunungan Bintang",
  "Puncak",
  "Puncak Jaya",
  "Sarmi",
  "Supiori",
  "Tolikara",
  "Waropen",
  "Yahukimo",
  "Yalimo",
  "Kota Jayapura",
  "Fakfak", //Provinsi Papua Barat
  "Kaimana",
  "Manokwari",
  "Manokwari Selatan",
  "Maybrat",
  "Pegunungan Arfak",
  "Raja Ampat",
  "Sorong",
  "Sorong Selatan",
  "Tambrauw",
  "Teluk Bintuni",
  "Teluk Wondama",
  "Kota Sorong"
  ];