List<String> kab = [
    "Cilacap"
    "Banyumas",
    "Purbalingga",
    "Banjarnegara",
    "Kebumen",
    "Purworejo",
    "Wonosobo",
    "Magelang",
    "Boyolali",
    "Klaten",
    "Sukoharjo",
    "Wonogiri",
    "Karanganyar",
    "Sragen",
    "Grobogan",
    "Blora",
    "Rembang",
    "Pati",
    "Kudus",
    "Jepara",
    "Demak",
    "Semarang",
    "Temanggung",
    "Kendal",
    "Batang",
    "Pekalongan",
    "Pemalang",
    "Tegal",
    "Brebes",
    "Kota Magelang",
    "Kota Surakarta",
    "Kota Salatiga",
    "Kota Semarang",
    "Kota Pekalongan",
    "Kota Tegal"
    "Bantul",
    "Gunungkidul",
    "Kulon Progo",
    "Sleman",
    "Kota Yogyakarta"
  ];