// this code is autogenerated using ansvia-vscode extension.
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

/// Model for Session
@immutable
class Session extends Equatable {
  // final int id;
  final int userId;
  final String token;

  Session(this.userId,this.token)
      : super([userId,token,]);

  Map<String, dynamic> toMap() {
    Map<String, dynamic> data = Map();
    // data["id"] = this.id;
    data["user_id"] = this.userId;
    data["token"] = this.token;
    return data;
  }

  static Session fromMap(Map<String, dynamic> data) {
    return Session(
        data['user_id'] as int, data['token'] as String);
  }

  Session copy({int userId, String token }) {
    return Session(userId ?? this.userId, token ?? this.token);
  }
}
